repository:
  root: "/home/etienne/nukekit_repo"
  subfolder:
    - Gizmo
    - Script

user:
  nuke_dir: "~/.nuke"

publishing:
  require_message: true
  auto_increment_patch: false
  
validation:
  check_dependencies: true
  warn_on_deprecated: true